# Custom aliases

alias ls='ls --color=auto'
alias ll='ls -lhF'
alias l='ls'
alias l.='ls -A'

alias rm="rm -I"

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias rset="reset && tmux clear-history"

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Lazy docker alias
# https://github.com/jesseduffield/lazydocker
#alias lazydocker="docker run --rm -it \
#  -v /var/run/docker.sock:/var/run/docker.sock \
#  -v ${HOME}/.config/lazydocker:/.config/jesseduffield/lazydocker \
#  lazyteam/lazydocker"

# Simple XClip-based clipboard piping into clipboard (Ctrl-V pastable)
alias copy="xclip -rmlastnl -selection clipboard"

# Virtualenv aliases
alias lsvirtualenv="lsvirtualenv -b"

# ps but just for me
alias mps="ps -U$(whoami) -H"

# DIVE docker container run invocation.
alias dive="docker run -ti --rm  -v /var/run/docker.sock:/var/run/docker.sock wagoodman/dive"
